DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK( ID bigint PRIMARY KEY NOT NULL, PRICE int, NAME varchar(50) );
INSERT INTO BOOK (ID,PRICE,NAME) VALUES (1,10,'Le ventre de paris');
INSERT INTO BOOK (ID,PRICE,NAME) VALUES (2,15,'Les miserables');
INSERT INTO BOOK (ID,PRICE,NAME) VALUES (3,5,'J accuse');
INSERT INTO BOOK (ID,PRICE,NAME) VALUES (4,20,'L assommoir');